# -*- coding: utf-8 -*-
"""Submission Predictive Analytics Telco Customer Churn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CE0w7sxNAihlexUQrQMaJEsa4OOvUsMe

# **1. Perkenalan Dataset**

Proyek ini menggunakan dataset Telco Customer Churn. Dataset ini diambil dari Kaggle yang dapat diakses melalui : https://www.kaggle.com/datasets/blastchar/telco-customer-churn. Berikut informasi mengenai datasetnya :
- Nama Dataset : Telco Customer Churn
- Jumlah Data  : 7,043
- Jumlah Fitur : 21

# **2. Import Library**
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

"""Pada tahap ini, kita mengimpor beberapa library Python yang akan digunakan untuk melakukan analisis dan pembangunan model machine learning:


*   pandas dan numpy untuk manipulasi data.
*   sklearn.model_selection untuk membagi dataset menjadi data latih dan data uji.
*   sklearn.preprocessing untuk melakukan encoding pada fitur kategorikal dan standardisasi pada fitur numerik.
*   sklearn.tree dan sklearn.ensemble untuk membangun model Decision Tree dan Random Forest.
*   sklearn.metrics untuk evaluasi model dengan menggunakan classification report dan confusion matrix.
*   matplotlib.pyplot dan seaborn untuk visualisasi data.

# **3. Memuat Dataset**
"""

# load the dataset
url = 'https://raw.githubusercontent.com/abdlsykr/portfolio/refs/heads/main/Dicoding/Machine_Learning_Terapan/WA_Fn-UseC_-Telco-Customer-Churn.csv'
data = pd.read_csv(url)
data

"""Pada tahap ini, kita memuat dataset yang berisi data pelanggan Telco dari URL yang disediakan. Dataset ini digunakan untuk memprediksi customer churn. Setelah dataset dimuat, kita menampilkan data untuk melihat beberapa baris pertama.

# **4. Exploratory Data Analysis (EDA)**
"""

data.info()

"""Metode info() digunakan untuk menampilkan informasi tentang dataset, termasuk jumlah baris, kolom, dan tipe data untuk setiap kolom. Ini membantu kita memahami struktur data secara keseluruhan."""

data['TotalCharges'] = pd.to_numeric(data['TotalCharges'], errors='coerce')
data['TotalCharges'].fillna(data['TotalCharges'].median(), inplace=True)

"""

*   Di sini, kita mengonversi kolom TotalCharges menjadi tipe data numerik menggunakan pd.to_numeric. Proses ini juga menangani data yang mungkin memiliki nilai non-numerik.
*   Selanjutnya, kita mengisi missing values pada kolom TotalCharges dengan nilai median. Pengisian dengan median dilakukan agar tidak mengubah distribusi data secara signifikan.

"""

data.drop('customerID', axis=1, inplace=True)

"""Pada tahap ini, kita menghapus kolom customerID karena kolom ini tidak berpengaruh pada prediksi churn dan hanya bertindak sebagai identifier unik untuk setiap pelanggan."""

data['SeniorCitizen'] = data['SeniorCitizen'].astype('category')

"""Fitur SeniorCitizen diubah menjadi tipe data kategori untuk menunjukkan bahwa ini adalah fitur kategorikal, bukan numerik. Hal ini berguna untuk model yang hanya membutuhkan fitur kategorikal untuk analisis."""

data.info()

data.describe()

"""Metode describe() digunakan untuk menghasilkan statistik deskriptif dari dataset, termasuk nilai mean, standar deviasi, min, max, dan kuartil. Ini memberikan gambaran umum mengenai distribusi fitur numerik."""

sns.boxplot(x=data['tenure'])

sns.boxplot(x=data['MonthlyCharges'])

sns.boxplot(x=data['TotalCharges'])

"""Visualisasi boxplot digunakan untuk memeriksa adanya outlier pada fitur numerik seperti tenure, MonthlyCharges, dan TotalCharges. Boxplot membantu kita melihat distribusi data dan nilai ekstrem."""

numerical_features = ['tenure', 'MonthlyCharges', 'TotalCharges']
categorical_features = ['SeniorCitizen', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']

for feature in categorical_features:
    count = data[feature].value_counts()
    percent = 100 * data[feature].value_counts(normalize=True)
    df = pd.DataFrame({'jumlah sampel': count, 'persentase': percent.round(1)})

    # Print the table for each feature
    print(f"Feature: {feature}")
    print(df)
    print("\n")

    # Plot bar chart for each feature
    count.plot(kind='bar', title=feature)
    plt.show()

"""Untuk fitur kategorikal, kita melakukan perhitungan jumlah dan persentase untuk setiap nilai unik. Hasilnya ditampilkan dalam bentuk tabel dan visualisasi grafik batang. Ini memberikan gambaran yang jelas tentang distribusi kategori untuk setiap fitur, seperti berapa banyak pelanggan yang memiliki pasangan atau menggunakan layanan internet tertentu."""

data.hist(bins=50, figsize=(20,15))
plt.show()

"""Histogram ini memberikan gambaran tentang distribusi dari tiga fitur numerik: tenure, MonthlyCharges, dan TotalCharges. Setiap grafik memperlihatkan frekuensi data pada rentang nilai tertentu.

1.   Histogram untuk tenure:

*   tenure menunjukkan distribusi pelanggan berdasarkan masa berlangganan mereka.
*   Terlihat ada dua kelompok besar dalam data:

 - Sebagian besar pelanggan memiliki tenure rendah (lebih sedikit dari 10 bulan).
 - Ada lonjakan besar pada tenure tinggi, yang menunjukkan ada banyak pelanggan yang telah berlangganan lebih dari 60 bulan (mungkin pelanggan yang setia).

2.   Histogram untuk MonthlyCharges:

*   Biaya bulanan (MonthlyCharges) menunjukkan distribusi yang relatif merata, namun ada lonjakan besar pada nilai sekitar 20 Dollar.
*   Banyak pelanggan membayar sekitar 20 Dollar hingga 80 Dollar per bulan, dan sebagian kecil membayar lebih dari 100 Dollar.
*   Ini menunjukkan adanya berbagai pilihan paket harga dan variasi biaya bulanan untuk pelanggan.

3.   Histogram untuk MonthlyCharges:

*   TotalCharges menunjukkan rentang nilai yang lebih besar, dengan sebagian besar pelanggan membayar di bawah 2000.
*   Terdapat outlier pada sisi kanan, yang menunjukkan beberapa pelanggan dengan total pembayaran yang jauh lebih tinggi dibandingkan dengan kebanyakan pelanggan lainnya. Boxplot ini menunjukkan distribusi yang lebih tersebar.







"""

cat_features = data.select_dtypes(include='object').columns.to_list()

for col in cat_features:
  sns.catplot(x=col, y="TotalCharges", kind="bar", dodge=False, height = 4, aspect = 3,  data=data, palette="Set3")
  plt.title("Rata-rata 'TotalCharges' Relatif terhadap - {}".format(col))

"""Bagian ini menunjukkan bagaimana kita dapat menangani fitur kategorikal untuk analisis lebih lanjut. Biasanya, kita akan melakukan Label Encoding atau One-Hot Encoding pada fitur kategorikal untuk mengonversinya menjadi format numerik yang bisa diproses oleh model."""

# Mengamati hubungan antar fitur numerik dengan fungsi pairplot()
sns.pairplot(data, diag_kind = 'kde')

"""Pada visualisasi ini, pairplot digunakan untuk menampilkan hubungan antar fitur numerik: tenure, MonthlyCharges, dan TotalCharges. Pairplot ini memberikan informasi tentang distribusi masing-masing fitur dan korelasi antar fitur dalam bentuk scatter plot dan plot distribusi (dengan jenis kde untuk diagonal).

*   Hubungan tenure dan TotalCharges menunjukkan bahwa pelanggan yang berlangganan lebih lama membayar lebih banyak secara total.
*   Distribusi biaya bulanan (MonthlyCharges) sebagian besar terpusat pada nilai menengah, dengan sedikit pelanggan yang membayar biaya yang sangat tinggi.
*   Tidak ada korelasi yang sangat kuat antara tenure dan MonthlyCharges, menunjukkan bahwa pelanggan yang membayar lebih rendah atau lebih tinggi tidak selalu memiliki masa berlangganan yang panjang atau pendek.




"""

plt.figure(figsize=(10, 8))
correlation_matrix = data[numerical_features].corr().round(2)

# Untuk menge-print nilai di dalam kotak, gunakan parameter anot=True
sns.heatmap(data=correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5, )
plt.title("Correlation Matrix untuk Fitur Numerik ", size=20)

"""Pada visualisasi ini, kita menggunakan Matriks Korelasi untuk menunjukkan hubungan antar fitur numerik: tenure, MonthlyCharges, dan TotalCharges. Matriks korelasi mengukur sejauh mana dua fitur berhubungan satu sama lain, dengan nilai berkisar antara -1 (hubungan negatif sempurna) hingga +1 (hubungan positif sempurna).

*   Hubungan yang paling kuat terlihat antara tenure dan TotalCharges (0.83), yang berarti bahwa pelanggan yang berlangganan lebih lama cenderung memiliki total biaya yang lebih tinggi.
*   Hubungan antara MonthlyCharges dan TotalCharges juga cukup signifikan (0.65), mengindikasikan bahwa pelanggan yang membayar lebih banyak setiap bulan biasanya juga memiliki total biaya yang lebih tinggi.

# **5. Data Preprocessing**
"""

label_encoders = {}
categorical_cols = data.select_dtypes(include=['object', 'category']).columns
for col in categorical_cols:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

"""Pada tahap ini, kita menggunakan Label Encoding untuk mengonversi fitur kategorikal menjadi angka. Proses ini diperlukan agar algoritma machine learning dapat memproses data numerik."""

X = data.drop('Churn', axis=1)
y = data['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

print(f'Total # of sample in whole dataset: {len(X)}')
print(f'Total # of sample in train dataset: {len(X_train)}')
print(f'Total # of sample in test dataset: {len(X_test)}')

"""Kita membagi dataset menjadi dua bagian: data latih (80%) dan data uji (20%). Data latih digunakan untuk melatih model, sementara data uji digunakan untuk mengevaluasi kinerja model setelah pelatihan."""

scaler = StandardScaler()
numerical_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

"""Standardisasi dilakukan untuk menormalkan fitur numerik seperti tenure, MonthlyCharges, dan TotalCharges, yang penting untuk model seperti KNN atau Logistic Regression. Meskipun Decision Tree dan Random Forest tidak sensitif terhadap skala, ini adalah langkah yang baik untuk memastikan model lainnya dapat bekerja dengan baik.

# **6. Melatih dan Mengevaluasi Model**
"""

# Decision Tree
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)

print("Decision Tree Classification Report:")
print(classification_report(y_test, dt_pred))

"""Decision Tree:

Lebih efektif dalam mendeteksi kelas 0 (recall tinggi), tetapi memiliki precision rendah untuk kelas 1, yang menyebabkan banyak kesalahan dalam mengklasifikasikan kelas 1. Akurasi keseluruhan juga lebih rendah dibandingkan dengan Random Forest.
"""

# Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

print("Random Forest Classification Report:")
print(classification_report(y_test, rf_pred))

"""Random Forest:

Memiliki kinerja yang lebih seimbang secara keseluruhan, terutama dengan precision yang lebih tinggi untuk kelas 1 dan recall yang sangat baik untuk kelas 0. Meskipun ada sedikit kekurangan dalam mendeteksi kelas 1 (recall lebih rendah), Random Forest memiliki akurasi lebih tinggi dan performa yang lebih baik secara keseluruhan.
"""

cm_rf = confusion_matrix(y_test, rf_pred)
plt.figure(figsize=(6,4))
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Blues')
plt.title('Confusion Matrix - Random Forest')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""Model Random Forest memiliki akurasi yang baik, namun masih perlu perbaikan pada deteksi kelas 1, terlihat dari tingginya jumlah False Negatives (198), yang menunjukkan banyak data kelas 1 yang tidak terdeteksi dengan benar. Model ini cenderung lebih baik dalam mengklasifikasikan kelas 0, tetapi False Positives (91) dan False Negatives (198) menunjukkan adanya trade-off antara precision dan recall yang perlu ditingkatkan."""

feature_importances = pd.DataFrame(rf_model.feature_importances_,
                                   index = X_train.columns,
                                   columns=['importance']).sort_values('importance', ascending=False)


feature_importances.head(10).plot(kind='barh', figsize=(10,6))
plt.title('Top 10 Feature Importances - Random Forest')
plt.gca().invert_yaxis()
plt.show()

"""Dari grafik feature importance yang ditampilkan, kita dapat melihat perbandingan kepentingan fitur-fitur dalam model Random Forest yang digunakan untuk prediksi.

*   TotalCharges memiliki feature importance tertinggi, menunjukkan bahwa ini adalah fitur yang paling mempengaruhi keputusan model dalam klasifikasi.
*   MonthlyCharges dan tenure juga memiliki nilai feature importance yang signifikan, yang berarti kedua fitur ini memberikan kontribusi besar dalam memprediksi output model.
*   Contract, PaymentMethod, dan OnlineSecurity juga penting, meskipun dengan nilai yang lebih rendah dibandingkan tiga fitur pertama.
*   Fitur seperti gender, OnlineBackup, dan InternetService memiliki importance lebih rendah, yang menunjukkan bahwa fitur-fitur ini tidak memberikan kontribusi yang signifikan dalam keputusan model.




"""