# -*- coding: utf-8 -*-
"""Submission_Akhir Klasifikasi Gambar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9GOdi9_Mp4n3dEL1Wf9I563P9Zsr5PX

# Proyek Klasifikasi Gambar: Shells or Pebbles: An Image Classification Dataset
- **Nama:** Abdul Syukur Kamaruddin
- **Email:** abdulsyukursyam@gmail.com
- **ID Dicoding:** abdlsykr

## Import Semua Packages/Library yang Digunakan
"""

from tensorflow.keras.applications import InceptionV3
from tensorflow.keras import layers, models
from tensorflow.keras.models import Sequential
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, LearningRateScheduler, Callback
import tensorflow as tf
import numpy as np
import os
import shutil
from sklearn.model_selection import train_test_split

"""## Data Preparation

### Data Loading
"""

!pip install -q kaggle

from google.colab import files
files.upload()  # Upload file kaggle.json

os.makedirs('/root/.kaggle', exist_ok=True)
!cp kaggle.json /root/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json

!kaggle datasets download -d vencerlanz09/shells-or-pebbles-an-image-classification-dataset
!unzip shells-or-pebbles-an-image-classification-dataset.zip -d dataset/

print(os.listdir('dataset/'))

"""### Data Preprocessing

#### Split Dataset
"""

pebbles_path = 'dataset/Pebbles'
shells_path = 'dataset/Shells'

os.makedirs('dataset/train/Pebbles', exist_ok=True)
os.makedirs('dataset/train/Shells', exist_ok=True)
os.makedirs('dataset/test/Pebbles', exist_ok=True)
os.makedirs('dataset/test/Shells', exist_ok=True)

pebbles_files = [os.path.join(pebbles_path, f) for f in os.listdir(pebbles_path) if f.endswith('.jpg') or f.endswith('.png')]
shells_files = [os.path.join(shells_path, f) for f in os.listdir(shells_path) if f.endswith('.jpg') or f.endswith('.png')]

pebbles_train, pebbles_test = train_test_split(pebbles_files, test_size=0.2, random_state=42)
shells_train, shells_test = train_test_split(shells_files, test_size=0.2, random_state=42)

for file in pebbles_train:
    shutil.copy(file, 'dataset/train/Pebbles/')
for file in shells_train:
    shutil.copy(file, 'dataset/train/Shells/')
for file in pebbles_test:
    shutil.copy(file, 'dataset/test/Pebbles/')
for file in shells_test:
    shutil.copy(file, 'dataset/test/Shells/')

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=40,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest',
    brightness_range=[0.5, 1.5],
    validation_split=0.2
)

val_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    'dataset/train', target_size=(299, 299), batch_size=32, class_mode='binary', subset='training'
)

validation_generator = val_datagen.flow_from_directory(
    'dataset/train', target_size=(299, 299), batch_size=32, class_mode='binary', subset='validation'
)

test_generator = test_datagen.flow_from_directory(
    'dataset/test', target_size=(299, 299), batch_size=32, class_mode='binary'
)

steps_per_epoch = train_generator.samples // train_generator.batch_size
validation_steps = validation_generator.samples // validation_generator.batch_size

"""## Modelling"""

base_model = InceptionV3(weights='imagenet', include_top=False, input_shape=(299, 299, 3))

model = Sequential([
    base_model,
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.5),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

base_model.trainable = False
for layer in base_model.layers[-4:]:
    layer.trainable = True

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

class CustomCallbacks(Callback):
    def on_epoch_end(self, epoch, logs=None):
        logs = logs or {}
        accuracy = logs.get("accuracy", 0)

        if accuracy > 0.85:
            print(f"\nPelatihan berhenti karena akurasi training ({accuracy:.4f}) telah melewati 0.85.")
            self.model.stop_training = True

def lr_scheduler(epoch, lr):
    if epoch > 30:
        return lr * 0.5
    return lr

lr_callback = LearningRateScheduler(lr_scheduler)

callbacks = [CustomCallbacks(), lr_callback]

history = model.fit(
    train_generator,
    steps_per_epoch=steps_per_epoch,
    epochs=30,
    validation_data=validation_generator,
    validation_steps=validation_steps,
    callbacks=callbacks
)

"""## Evaluasi dan Visualisasi"""

plt.plot(history.history['accuracy'], label='Akurasi Training')
plt.plot(history.history['val_accuracy'], label='Akurasi Validation')
plt.xlabel('Epoch')
plt.ylabel('Akurasi')
plt.legend(loc='lower right')
plt.title('Akurasi Model')
plt.show()

plt.plot(history.history['loss'], label='Loss Training')
plt.plot(history.history['val_loss'], label='Loss Validation')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(loc='upper right')
plt.title('Loss Model')
plt.show()

test_loss, test_accuracy = model.evaluate(test_generator)
print(f"\nAkurasi pada data testing: {test_accuracy:.4f}")

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# Ambil prediksi dari model
test_generator.reset()
y_pred_probs = model.predict(test_generator, verbose=1)
y_pred = (y_pred_probs > 0.5).astype(int).flatten()

# Label sebenarnya
y_true = test_generator.classes

# Nama kelas
class_labels = list(test_generator.class_indices.keys())

# Classification Report
print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=class_labels))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=class_labels, yticklabels=class_labels)
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")
plt.show()

"""## Konversi Model"""

# Membuat labels.txt berdasarkan kelas dari train_generator
label_map = train_generator.class_indices
sorted_labels = sorted(label_map, key=label_map.get)  # Urut berdasarkan indeks

with open("labels.txt", "w") as f:
    for label in sorted_labels:
        f.write(label + "\n")

print("labels.txt berhasil dibuat dengan label:", sorted_labels)

save_path = '/content/mymodel/'
tf.saved_model.save(model, save_path)

!pip install tensorflowjs

model.save('pebblesorshells.h5')

!tensorflowjs_converter --input_format=keras pebblesorshells.h5 tfjs_model

import os
os.listdir('tfjs_model')

# Memuat model Keras yang sudah disimpan
model = tf.keras.models.load_model('pebblesorshells.h5')

# Konversi model Keras ke TensorFlow Lite
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Simpan model TensorFlow Lite ke file
with open('pebblesorshells_model.tflite', 'wb') as f:
    f.write(tflite_model)

pip freeze requirements.txt

"""## Inference (Optional)"""

